apiVersion: apps/v1
kind: Deployment

metadata:
  name: java-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: java-app

  template:
    metadata:
      labels:
        app: java-app

    spec:
      containers:
      - name: java-app
        image: 505342112116.dkr.ecr.ap-south-1.amazonaws.com/java-app:f6b3ec4bd5776359ee9d3428132dd98363ee3f67
kind: Deployment

metadata:
  name: java-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: java-app

  template:
    metadata:
      labels:
        app: java-app

    spec:
      containers:
      - name: java-app
        image: 505342112116.dkr.ecr.ap-south-1.amazonaws.com/java-app:f6b3ec4bd5776359ee9d3428132dd98363ee3f67
        ports:
        - containerPort: 8080
        ports:
        - containerPort: 8080
