apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: java-app

spec:
  project: default

  source:
    repoURL: https://github.com/madhumallela99/Github-actions-Argocd
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:

    automated:
      prune: true
      selfHeal: true
